### ISSUE TITLE
Integrate TUI option for testing zmq subscriptions to events plz

### ISSUE THREAD

**Issue by imylomylo** [tonymorony/komodo_cryptoconditions_tui#2]
Hi Tony

Can you add an option to TUI that just subscribes to basic events like this example:

https://github.com/bitcoin/bitcoin/blob/master/contrib/zmq/zmq_sub.py

I think we'll want to test ZMQ event subscriptions for stuff, and if TUI has it built in to modify quickly or make a new option quickly - it will make the event features for devs accessible without any fuss.

Cheers

**Comment by tonymorony** [comment]
Hi Mylo @imylomylo ,

Thank you, will wrap my head over it asap. 

Could you point me on some application / needed or desirable use-case so I'll try to prototype it?

Am I understand correctly that in TUI should be a queue server and client will be implemented not on TUI side?

I have some places where I save stuff to files - probably these places is from where I can start.

**Comment by imylomylo** [comment]
Hi Tony,

There are two use cases from satinder (cc-assets) and alright when i've
chatted to them about it.   The one for kmdlabs is to make it easier to
subscribe to chain migration events.
With the ROGUE game, there will also be uses of event based notifications -
player dying, tournament mode (buy-in) creation.

OK I'll have another look because request was last week - just wanted to
know whether you'd be interested in integrating or if it was something not
interested.
Because the sample I found was in python, it could be an easy zmq
integration to show the TUI being integrated with events.
If TUI can do it, GUI can do it - and the TUI can be used for reference.

Will respond here or in discord with more info.

Thanks!!
