### ISSUE TITLE
Warrior did not save, lost all warrior progress

### ISSUE THREAD

**Issue by wookie25** [tonymorony/komodo_cryptoconditions_tui#25]
game txid: 
d90130190ee057756e325148e94925b6021a19ad01fa28d40eb3d952b9e01cc3

Running on a MacOS

**Comment by tonymorony** [comment]
I wonder it's not actually on this point since a lot of things were re-worked on komodod side.
I hope that daemon update to the latest will allow to not lose warriors (at least not so often).
